### ISSUE TITLE
Mobile Issues

### ISSUE THREAD

**Issue by valentine195** [javalent/obsidian-leaflet#168]
Please use this issue as a catch all for mobile issues. 

1. [x] Touch / drag events are propagating to main app
2. [ ] Cannot do any interactions that require key modifiers
3. [x] Full screen button needs to be removed
4. [x] Leaflet stuck on top always ([comment](https://github.com/valentine195/obsidian-leaflet-plugin/issues/168#issuecomment-884650010))
5. [x] Filter markers button gets stuck open

**Comment by SlRvb** [comment]
4. Leaflet stuck on top always

It covers the sidebars and the popover when clicking on one of the pins.

https://user-images.githubusercontent.com/54087190/126590171-645c3a37-b2b2-4183-8143-172bdbd066ed.MOV

**Comment by valentine195** [comment]
> 1. Leaflet stuck on top always
> 
> It covers the sidebars and the popover when clicking on one of the pins.

This should be fixed in 3.20.2
