### ISSUE TITLE
Explore possibility of using Obsidian query language to find markers

### ISSUE THREAD

**Issue by valentine195** [javalent/obsidian-leaflet#172]
Currently it is not exposed in the API. 

Incremental Writing seems to use it in this function: 

https://github.com/bjsi/incremental-writing/blob/beb3e9ebca9104a672bcbfb99d57e482169524e3/src/main.ts#L93

**Comment by Moonbase59** [comment]
Heretic question: Do we really need yet another query possibility? What would be the advantages?

**Comment by valentine195** [comment]
One advantage - exclusions.

Imagine:

`query: tag:tag1, -tag:tag2, path: Folder/Folder 2`
