### ISSUE TITLE
Is it possible to add a latitude and longitude positioning function?

### ISSUE THREAD

**Issue by zhl111** [javalent/obsidian-leaflet#229]
And a search function. Refer to the plugin open map view
What I mean is that the plugin "open map view" allows you to set the exact latitude and longitude and thus position yourself on the map. The plugin "leaflet" only allows you to drag and drop files to locate them, which is very annoying when there are many addresses.
![image](https://user-images.githubusercontent.com/29135984/134806977-1ba4e8ef-1774-47c0-9ad5-49cb42aca907.png)

![image](https://user-images.githubusercontent.com/29135984/134803953-9eb93932-f1ff-49c7-8407-729250a2b86c.png)

**Comment by valentine195** [comment]
This is possible, I will investigate. There are quite a lot of buttons cluttering the UI at the moment, so this may need to wait until I can reconfigure the UI a bit.
