### ISSUE TITLE
Use frontmatter to find notes

### ISSUE THREAD

**Issue by Signynt** [javalent/obsidian-leaflet#284]
I keep the locations I visit in my front matter of my daily notes, so that they can easily be queried by dataview. Example:

```
---
visited: ["[[Restaurant]]", "[[Park]]"]
---
```

It would be great if I'd be able to show those notes as the map markers, similar to `linksFrom: ` but using the notes listed under that front matter item. Since currently using Dataview for finding notes or tags is possible this seems like it would be doable.
Another alternative that would be even more powerful would be able to put in dataview queries directly into leaflet!

**Comment by valentine195** [comment]
> dataview queries directly into leaflet!

Yes, I would love this, but it will require [this issue](https://github.com/blacksmithgu/obsidian-dataview/issues/374) to be closed which I have had open for months.

I will think about how to implement this, shouldn't be too hard, just need the time.

**Comment by sigrunixia** [comment]
Still love the idea of this @valentine195 ? :)
