### ISSUE TITLE
Add WMS as a new map source type

### ISSUE THREAD

**Issue by kalmir** [javalent/obsidian-leaflet#294]
It would be great if the plugin could work not only with XYZ Tile Servers but also with Web Map Service (WMS) Servers.

My use case is offline work in intranet environment where maps are served by ArcGis. Supposedly ArcGis can passively work with XYZ but is not set-up to provide as server in XYZ Tile Server format.

(So this is a feature request.)

**Comment by sigrunixia** [comment]
If someone is interested in creating the appropriate tile layer, I'll leave this open. 

Here is the documentation by leaflet.js on [supporting WMS](https://leafletjs.com/examples/wms/wms.html).
