### ISSUE TITLE
Saving multiple tile sets globally

### ISSUE THREAD

**Issue by kepano** [javalent/obsidian-leaflet#301]
I love the feature of being able to have multiple tile sets available for a map.

Since I pretty much always use the same sets of tiles across all of my maps, it would be useful to be able to define these globally in the plugin settings

**Comment by valentine195** [comment]
You can specify the default tile server in settings, unless I misunderstood your request

**Comment by kepano** [comment]
Currently you can specify one default. But I am suggesting saving multiple tile sets globally, e.g. 

- Transit
- Hills
- Satellite

You can do this by adding the tile sets in the query, which gives you a nice picker menu on the map (screenshot below). The limitation is that you can't add these at the global level, so it requires adding that preference to every query.

<img width="443" alt="Screen Shot 2022-05-01 at 12 11 47 PM" src="https://user-images.githubusercontent.com/10565871/166160923-33443c57-cf29-4eef-8fd8-be76aa05be2a.png">

**Comment by sigrunixia** [comment]
@valentine195 Is this one resolved?
