### ISSUE TITLE
Unusable in popout windows (Obsidian version 0.15.6)

### ISSUE THREAD

**Issue by Pachtjuilaard** [javalent/obsidian-leaflet#307]
Map can't be panned or properly interacted with when in a popout window. Going full screen from a popout window makes zooming also broken. Pins with notes still seem to work as intended though.

I'd love to use Leaflet in secondary windows, so we can put interactive D&D battlemaps on a HDMI-connected TV screen while having my DM notes on my laptop!

**Comment by elhappi** [comment]
I think this problem still exists. I just wanted to do what @Pachtjuilaard described and the controls are off in the second window and leaflets cannot be controlled anymore.

![image](https://github.com/user-attachments/assets/019ee6d3-aef8-40ee-91e7-5f00aed6cfaa)

**Comment by elhappi** [comment]
Seeing this error in the console when I try to move the map in the second window:

![image](https://github.com/user-attachments/assets/2445a7fa-a765-4c0a-9263-2d9b9429a6d8)

Not sure how to reopen this in case anyone wants to look into the problem.
