### ISSUE TITLE
Can't pan

### ISSUE THREAD

**Issue by ThatRickGuy** [javalent/obsidian-leaflet#318]
Hey there, maybe I'm doing something wrong here, but I can't figure out how to pan the map. Right clicking creates a market, mouse wheel zooms in and out, left clicking does nothing. It seems like left click and drag should be a pan interaction, but I've got nothing. 

Windows 11
Obsidian 0.15.9
Obsidian Leaflet 5.0.3

```leaflet
id: leaflet-map
image: [[Khorvaire2.jpg]]
minZoom: 1
maxZoom: 10
defaultZoom: 6
unit: meters
scale: 1
height: 100%
width:100%
```

**Comment by v0v3s** [comment]
Since it is closed is there a solution? I can't seem to pan either. The only way it works is with arrow keys.
