### ISSUE TITLE
Two feature requests

### ISSUE THREAD

**Issue by Calorion** [javalent/obsidian-leaflet#327]
1. Please provide an option to remove the icon in the toolbar
1. Please rename the plugin to "Leaflet" rather than "Obsidian Leaflet."

**Comment by valentine195** [comment]
Why do you want the plugin renamed?

**Comment by Calorion** [comment]
Because if everyone named their plugins "Obsidian X," finding them would be rather difficult. And indeed, I sometimes scroll through my list of plugins looking for "L", only to realize it's under "O."

**Comment by sigrunixia** [comment]
1. Is handled by Obsidian Natively


2. While Obsidian does now recommend plugin developers do not name their plugins with Obsidian in the title, renaming it to just leaflet would then infringe on the brand context of Leaflet.js. 

I understand your frustration. It can get annoying sometimes. The updated community plugins page helps with this feature, as does one of Valentines other plugins, the nifty https://github.com/valentine195/obsidian-settings-search.
