### ISSUE TITLE
Same markers being put on every map on every note

### ISSUE THREAD

**Issue by AweSamLoser** [javalent/obsidian-leaflet#332]
Hi there,

So, I will be using multiple maps across multiple notes as I am using this for TTRPGs. I have found that the markers I have created for the first map are being placed on all the subsequent maps. Is there a way for stop this from happening?

Thank you in advance.

**Comment by valentine195** [comment]
Do all the maps share the same ID?

**Comment by AweSamLoser** [comment]
That they do, my mistake.

Thank you haha
