### ISSUE TITLE
Feature Request: Distance with multiple nodes

### ISSUE THREAD

**Issue by paulo-roger** [javalent/obsidian-leaflet#335]
So I was thinking if it is possible to ad the possibility to have multiple nodes when alt+clicking to get the distance between points, so the user could for instance calculate the actual distance of a road that make curves and such.
Also would be nice to display both, the total and partial distances (between nodes).

**Comment by dfaggioli** [comment]
This has been implemented already, by https://github.com/javalent/obsidian-leaflet/commit/fbdf5f095722b408ce4899bca9e8a23555a57111 and https://github.com/javalent/obsidian-leaflet/commit/6bc541f859c46f4ce52be8a4df602f935ef94e1c ... Hasn't it?

**Comment by valentine195** [comment]
Yes, thanks.
