### ISSUE TITLE
Provide export from polygon to geojson

### ISSUE THREAD

**Issue by chabad360** [javalent/obsidian-leaflet#337]
leaflet has the ability to convert any shape as a geojson (using `.toGeoJSON`). It would be really helpful if we could draw shapes and then export them as geojson so they can be actually useful. 

I've been trying to figure out if there is a way that I can do this via the console, but I've not been able to figure it out.

**Comment by sigrunixia** [comment]
This was implemented in https://github.com/javalent/obsidian-leaflet/commit/ea165cca2fa3e8e49bcdd0b41fa191c32c36ea3a
