### ISSUE TITLE
Crash when a note with a Leaflet map is opened/moved to a second window

### ISSUE THREAD

**Issue by dfaggioli** [javalent/obsidian-leaflet#371]
The context is showing a map to players. For doing that, I've been putting the map in a note and then clicking "Move to new window". I've tried with the "Second Window" plugin, but the results are the same.

The note appears in the new window, and the map is there. But it's not fully-functional, i.e:
- pins can't be moved
- the map can be zoomed, but can't be moved
- clicking on any of the following button leads to a crash (i.e., the window disappears, but I don't see anything in the console):
  - Reset Zoom
  - Fullscreen
  - Show all markers
  - Lock/Unlock
  - Draw

I don't know if this can be relevant, but the controls for showing a different layer and for filtering the pins work. And also right clicking on a pin for editing it does (while dragging it around doesn't).

**Comment by Lewas5372** [comment]
I dont get a crash.  All I get when I have a note that is nothing but the leaflet map, when I go to show it in another window through the second window plug in, nothing is shown.

**Comment by dfaggioli** [comment]
> I dont get a crash. All I get when I have a note that is nothing but the leaflet map, when I go to show it in another window through the second window plug in, nothing is shown.

Yes, if I use Second Window, the content of the opened window looks like it's rendered in HTML or something like that. So I do see some content, but not the various dynamic stuff, which of course includes Leaflet maps.

Without using Second Window, I still get the crash. Basically (as described above), the Leaflet "object" is only halfway functional. It shows, and I can zoom with the mouse wheel and things like that. But the UI icons are looking weird, and as soon as I click, for example, on "Unlock" (but also on others), the window crashes, and a prompt asking me if I want to open a new vault shows.

BTW, @valentine195 , I know you're busy and I absolutely don't want to sound pushy... but if there's anything I can do to help testing and debugging this, just let me know. :-) I've tried to check the console, but there's nothing there.

**Comment by Batres3** [comment]
Im not sure why this is closed, this issue still happens, at least to me
