### ISSUE TITLE
[Outreach]: Attempt to bring Compatibility with Map View

### ISSUE THREAD

**Issue by sigrunixia** [javalent/obsidian-leaflet#384]
With ongoing development between the two Maps, it stands to reason one can help the other and vice versa. Are you amendable to seeing if the dev will work with us to not only fix the compatibility bug, but collaboration going forward?

---

              Hmmm, further digging on the MapView Github site reveals an issue of incompatibility between Leaflet and MapView, discovered last month

https://github.com/esm7/obsidian-map-view/issues/154#issuecomment-1500915565

Following advice from that issue, disabling Leaflet brings MapView back to life.

_Originally posted by @erex in https://github.com/javalent/obsidian-leaflet/issues/378#issuecomment-1535828840_

**Comment by valentine195** [comment]
We’ve dealt with this issue together before. It’s an unfortunate side effect of how the LeafletJS module is coded. I might need to revert back to the webpack build process until I can figure out a workaround in esbuild.
