### ISSUE TITLE
[Bug]: Issues caused by another plugin.

### ISSUE THREAD

**Issue by zhl111** [javalent/obsidian-leaflet#385]
https://github.com/nothingislost/obsidian-hover-editor/issues/213

**Comment by pjeby** [comment]
A description of the underlying problem can be found [here](https://github.com/nothingislost/obsidian-hover-editor/issues/213#issuecomment-1539029507) -- Obsidian is now adding the setting tab asynchronously, which means that the disable/enable of the core preview plugin by both Hover Editor and Leaflet schedules two addSettingTab() calls that happen together after both HE and L have done their disable+enable.  Likely the simple fix will be to patch addSettingTab to refuse duplicate adds; the more complex (but safer) fix would be that *both* HE and L would need to wait for the setting tab to exist before calling disable+enable.

(The main difference between these approaches is that the latter would be more robust to future changes in the logic of the Page Preview plugin's onEnable() method.)

**Comment by pjeby** [comment]
Hm.  I may have spoken too soon.  It looks like maybe Leaflet is doing a bunch of enable/disable stuff that it doesn't actually need to?  The around(HoverPopover.prototype) part is all that's really needed to do what it appears to be doing [here](https://github.com/javalent/obsidian-leaflet/blob/33210eff69d14f991b8ed8dd83e3eb9e2a1af922/src/main.ts#L262).  That is, it looks like you could just rewrite the method like so:

```ts
 patchLinkHover() {
        const uninstaller = around(HoverPopover.prototype, {
            onShow(old: Function) {
                return function () {
                    if (
                        this.parent?.state?.source ==
                        OBSIDIAN_LEAFLET_POPOVER_SOURCE
                    ) {
                        this.hoverEl.addClass("obsidian-leaflet-popover");
                    }
                    return old.call(this);
                };
            }
        });
        this.register(uninstaller);
    }
```

That is, just literally delete the rest of the method and the type definitions for internalPlugins.  This would be safer than any of my previous ideas since it would avoid the conflict altogether rather than working around it.

**Comment by valentine195** [comment]
I tried that but I don’t think it was being respected without reloading the page preview plugin - not 100% sure, it was awhile ago. 

I did investigate this a bit when I had a few minutes and noticed the new behavior. What confused me is it didn’t happen in English. Do you know why that would be?

**Comment by valentine195** [comment]
> Given that you're only patching the prototype onShow, there shouldn't be anything that would require the enable/disable.

Unfortunately I don’t see my patch occur if I don’t cycle the page preview plugin when HE is enabled. Could be a plugin load order issue there. 

> AFAICT Leaflet is only adding a class to the HTML of created popovers, and this doesn't affect any event handlers.

correct

> I can confirm the issue occurs in English, though - you have to start Obsidian with both HE and Leaflet enabled

I tried several times to get this to occur in English and never replicated it. I was about to just close the issue until I decided to try a different language just to make sure.

**Comment by pjeby** [comment]
> Unfortunately I don’t see my patch occur if I don’t cycle the page preview plugin when HE is enabled.

Maybe I'm misunderstanding things, but AFAICT Leaflet's onShow() patch doesn't do anything when Hover Editor is enabled.  Hover Editor uses a subclass of HoverPopover that doesn't use the base class's onShow implementation, so IIUC the patch would never affect Hover Editor, only non-Hover Editor popups.
