### ISSUE TITLE
[Feature Request]: Rearrange customized Map Marker

### ISSUE THREAD

**Issue by Missionary2112** [javalent/obsidian-leaflet#398]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I would like to rearrange the customized map marker so the frequently used ones stay on top.

### Current behaviour

I cannot rearrange the map marker order.

### Reproduction

Hold & drag the customized map marker to rearrange the order.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

5.6.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by sigrunixia** [comment]
Feature requests for this repo is currently close. I'll add this to something we may consider internally, but am otherwise closing this post. The feature request template and pin will be updated when feature requests return.
