### ISSUE TITLE
🐞 Perhaps we will need a more "detailed" map

### ISSUE THREAD

**Issue by YukZhao** [javalent/obsidian-leaflet#444]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When using the Amap to access real-world maps, I want to zoom in to a very detailed level due to personal needs. Therefore, I set the "maxzoom" to 25, but in reality, when zooming beyond level 18, it fails to display the content correctly. 
I suspect this might not be a bug, but rather limitations I encountered in my usage. I'm unsure if this issue has been addressed or if it's due to my improper settings. If it's related to settings, could you guide me on how to configure it correctly to achieve my desired outcome? 
Thank you very much.

### Current behaviour

![issue](https://github.com/javalent/obsidian-leaflet/assets/104962249/d105acb5-fbb4-48c4-bb16-a95757502852)

### Reproduction

```leaflet
id: hangzhou
osmLayer: false 
tileServer: http://webrd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z} 
tileSubdomains: ["1", "2", "3", "4"]
lat: 30
long: 120
height: 800px 
width: 100% 
defaultZoom: 14
maxzoom: 25
minzoom: 1 
unit: meters 
scale: 1 
zoomDelta: 1
```

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.12 and 1.5.11

### Plugin Version

6.0.5

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
This is an issue with your tile server. They probably don’t have tiles at that resolution.
