### ISSUE TITLE
🐞Opening Canvas creates a note

### ISSUE THREAD

**Issue by LeonardoCarolo** [javalent/obsidian-leaflet#451]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When selecting a file to go to through the marker, if a canvas is selected, it should open the canvas file.

### Current behaviour

Instead of opening a Canvas through the marker, it creates an empty note of the same name.

### Reproduction

1. Create a marker
2. Assign the target file as a canvas
3. Click the marker

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.6.5

### Plugin Version

6.0.5

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by meisterbierkules** [comment]
Just in case someone else finds this issue: As a canvas is not the typical markdown file the link needs to be "filename.canvas". Obsidian won't add the file extension even if the file was directly selected in the dialog.
