### ISSUE TITLE
Usability issues with markers that are close together

### ISSUE THREAD

**Issue by valentine195** [javalent/obsidian-leaflet#67]
Investigate if it's possible to make a "combined" marker that could group close together markers at zoom levels if they are overlapping, and display the grouped markers in the tooltip.

**Comment by Moonbase59** [comment]
Probably too complicated, one can always use the mouse wheel to zoom around. Google Maps isn’t better …

**Comment by valentine195** [comment]
> Google Maps isn’t better …

But we could be! 😉

**Comment by Moonbase59** [comment]
Hee hhe. Playing around with all the new features (and updating my friends’ notes), I just detected two friends living in exact the same house. Only _one_ (which is topmost, by chance) can be selected.

You’re probably right. If it’s doable …

**Comment by pixelart7** [comment]
I'm actually researching if this is possible since one of my use-case is a location-based journal with more than 1000 markers near the same location.

I will fork and try to do it.
It might be possible with `L.markercluster` (http://leaflet.github.io/Leaflet.markercluster/)

**Comment by valentine195** [comment]
Interesting, I did not know this library existed. Thanks for letting me know!

**Comment by pixelart7** [comment]
Hey, I explored the code a little bit but I can't seem to understand where to edit. I'm fairly new to Obsidian plugin dev and Leaflet as a whole. I might need to leave it to you...

**Comment by valentine195** [comment]
No worries, I appreciate the effort. This would be a rather comprehensive change, anyway - probably not possible for someone other than me to tackle it.
